export const ROUTES = {
  AGENT_SKILLS_INDEX: "/.well-known/agent-skills/index.json",
  AGENT_SKILLS_SITE_SKILL: "/.well-known/agent-skills/site-skill.md",
  API_CATALOG: "/.well-known/api-catalog",
  API_STATUS: "/api/status",
  DOCS: "/docs",
  DOCS_BROWSER_SUPPORT: "/docs/browser-support",
  DOCS_COMPONENTS: "/docs/components",
  DOCS_INSTALLATION: "/docs/installation",
  DOCS_PAGE: "/docs/components/page",
  DOCS_REGISTRY: "/docs/registry",
  DOCS_THEME: "/docs/components/theme",
  DOCS_UI: "/docs/components/ui",
  HOME: "/",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  LLMS_MD: "/llms.md",
  MANIFEST: "/manifest.webmanifest",
  MCP: "/mcp",
  OPENAPI: "/openapi.json",
  REGISTRY: "/r/registry.json",
  ROBOTS: "/robots.txt",
  RSS: "/rss.xml",
  SITEMAP: "/sitemap.xml",
  SPONSOR: "/sponsor",
} as const;
