/**
 * Source of truth for registry.json (generated by scripts/build-registry.ts)
 * and for the site's catalog (home showcase, group index pages, llms.txt).
 *
 * Item names are `<group>/<slug>`, installed as `@transition-kit/<group>/<slug>`.
 * - core: the React 19.3 <ViewTransition> wrapper for the group.
 * - style: one CSS file (registry/<group>/styles/<slug>.css), merged into the
 *   user's global CSS by the shadcn CLI. Depends on the group's core.
 * - component: a ready-made control built on the core.
 */
export type ItemGroup = "theme" | "page" | "ui";
export type ItemKind = "core" | "style" | "component";

export interface ItemSource {
  /** `<group>/<slug>` */
  name: `${ItemGroup}/${string}`;
  title: string;
  description: string;
  group: ItemGroup;
  kind: ItemKind;
  /** Source files under registry/. Components and cores install to components/transitions/. */
  files: string[];
  /** CSS file under registry/, shipped as the item's `css`. */
  css?: string;
  /** Preview video under public/. */
  video?: string;
  isNew?: boolean;
}

const themeStyle = (
  slug: string,
  title: string,
  description: string,
  video: string,
  isNew = false
): ItemSource => ({
  css: `registry/theme/styles/${slug}.css`,
  description,
  files: [],
  group: "theme",
  isNew,
  kind: "style",
  name: `theme/${slug}`,
  title,
  video: `/demos/theme-toggles/${video}`,
});

const pageStyle = (
  slug: string,
  title: string,
  description: string,
  video: string,
  isNew = false
): ItemSource => ({
  css: `registry/page/styles/${slug}.css`,
  description,
  files: [],
  group: "page",
  isNew,
  kind: "style",
  name: `page/${slug}`,
  title,
  video: `/demos/page-transitions/${video}`,
});

const themeComponent = (
  slug: string,
  title: string,
  description: string
): ItemSource => ({
  description,
  files: [`registry/theme/${slug}.tsx`],
  group: "theme",
  kind: "component",
  name: `theme/${slug}`,
  title,
});

export const items: ItemSource[] = [
  {
    css: "registry/theme/theme-transition.css",
    description:
      "ThemeTransitionProvider and useThemeTransition: theme state animated by React's <ViewTransition>.",
    files: ["registry/theme/theme-transition.tsx"],
    group: "theme",
    kind: "core",
    name: "theme/theme-transition",
    title: "Theme Transition",
  },
  themeComponent(
    "theme-toggle-button",
    "Theme Toggle Button",
    "A sun and moon icon button that toggles the theme with any transition style."
  ),
  themeComponent(
    "theme-toggle-switch",
    "Theme Toggle Switch",
    "A switch that flips between light and dark with any transition style."
  ),
  themeComponent(
    "theme-switcher",
    "Theme Switcher",
    "A light, dark and system segmented control with any transition style."
  ),
  themeComponent(
    "animated-theme-toggler",
    "Animated Theme Toggler",
    "An icon button whose sun and moon morph while the theme transitions."
  ),
  themeStyle(
    "circle-reveal",
    "Circle Reveal",
    "An expanding circle reveals the new theme from the click point.",
    "circle-reveal.webm"
  ),
  themeStyle(
    "circle-blur",
    "Circle Blur",
    "A soft, blurred circle expands from the click point.",
    "circle-blur.webm"
  ),
  themeStyle(
    "polygon-reveal",
    "Polygon Reveal",
    "A clip-path polygon sweeps a geometric wipe across the page.",
    "polygon-reveal.webm"
  ),
  themeStyle(
    "star-reveal",
    "Star Reveal",
    "An expanding star-shaped mask reveals the new theme.",
    "star-reveal.webm"
  ),
  themeStyle(
    "heart-reveal",
    "Heart Reveal",
    "An expanding heart-shaped mask reveals the new theme.",
    "heart-reveal.webm"
  ),
  themeStyle(
    "diagonal-wipe",
    "Diagonal Wipe",
    "A diagonal band sweeps across the viewport.",
    "diagonal-wipe.webm"
  ),
  themeStyle(
    "checkerboard-reveal",
    "Checkerboard Reveal",
    "A checkerboard of tiles grows to reveal the new theme.",
    "checkerboard-reveal.webm"
  ),
  themeStyle(
    "ripple-reveal",
    "Ripple Reveal",
    "Concentric rings ripple outward from the click point.",
    "ripple-reveal.webm"
  ),
  themeStyle(
    "venetian-blinds",
    "Venetian Blinds",
    "Horizontal slats open one by one, like blinds.",
    "venetian-blinds-theme.webm"
  ),
  themeStyle(
    "spiral-reveal",
    "Spiral Reveal",
    "A spiral-shaped mask winds outward.",
    "spiral-reveal.webm"
  ),
  themeStyle(
    "wave-reveal",
    "Wave Reveal",
    "A wavy edge sweeps across the viewport.",
    "wave-reveal-theme.webm"
  ),
  themeStyle(
    "clock-wipe",
    "Clock Wipe",
    "A wedge sweeps clockwise around the viewport centre, like a clock hand.",
    "clock-wipe.mp4",
    true
  ),
  themeStyle(
    "gif-frog",
    "GIF Frog",
    "A dancing frog reveals the new theme through an expanding mask.",
    "gif-frog.webm"
  ),
  themeStyle(
    "gif-penguin",
    "GIF Penguin",
    "A dancing penguin reveals the new theme through an expanding mask.",
    "gif-penguin.webm"
  ),
  themeStyle(
    "gif-cat",
    "GIF Cat",
    "A dancing cat reveals the new theme through an expanding mask.",
    "gif-cat.webm"
  ),
  themeStyle(
    "gif-michael-jackson",
    "GIF Michael Jackson",
    "A moonwalk reveals the new theme through an expanding mask.",
    "gif-michael-jackson.webm"
  ),
  themeStyle(
    "gif-deadpool",
    "GIF Deadpool",
    "Deadpool breaks in through an expanding mask.",
    "gif-deadpool.webm"
  ),
  themeStyle(
    "gif-chika",
    "GIF Chika",
    "Chika's dance reveals the new theme through an expanding mask.",
    "gif-chika.webm"
  ),
  themeStyle(
    "gif-hakari-dance",
    "GIF Hakari Dance",
    "Hakari dances in through an expanding mask.",
    "gif-hakari.webm"
  ),
  {
    css: "registry/page/page-transition.css",
    description:
      "PageTransition and navigateWithTransition: route changes animated by React's <ViewTransition>.",
    files: ["registry/page/page-transition.tsx"],
    group: "page",
    kind: "core",
    name: "page/page-transition",
    title: "Page Transition",
  },
  pageStyle(
    "fade",
    "Fade",
    "The old page fades out as the new one fades in.",
    "fade.webm"
  ),
  pageStyle(
    "slide",
    "Slide",
    "Pages slide past each other; backward navigations reverse.",
    "slide.webm"
  ),
  pageStyle(
    "scale",
    "Scale",
    "The new page scales up while the old one fades out.",
    "scale.webm"
  ),
  pageStyle(
    "flip",
    "Flip",
    "A 3D card flip around the vertical axis.",
    "flip.webm"
  ),
  pageStyle(
    "blur",
    "Blur",
    "The old page blurs away while the new one sharpens in.",
    "blur.webm"
  ),
  pageStyle(
    "rotate",
    "Rotate",
    "The new page rotates in while the old one fades out.",
    "rotate.webm"
  ),
  pageStyle(
    "zoom",
    "Zoom",
    "The old page zooms out as the new one zooms in.",
    "zoom.webm"
  ),
  pageStyle(
    "curtain",
    "Curtain",
    "The new page opens out of a centre strip as the old one closes into it.",
    "curtain.webm"
  ),
  pageStyle(
    "cube",
    "Cube",
    "Pages turn around the faces of a 3D cube.",
    "cube.webm"
  ),
  pageStyle(
    "skew-slide",
    "Skew Slide",
    "Pages skew as they slide past each other.",
    "skew-slide.webm"
  ),
  pageStyle(
    "page-curl",
    "Page Curl",
    "The old page curls up from the corner like a book page.",
    "page-curl.webm"
  ),
  pageStyle(
    "accordion",
    "Accordion",
    "The old page folds shut towards one edge as the new one unfolds from it.",
    "accordian.webm"
  ),
  pageStyle(
    "doorway",
    "Doorway",
    "The old page swings away on a hinge, revealing the new one.",
    "doorway.webm"
  ),
  pageStyle(
    "book-flip",
    "Book Flip",
    "The new page turns over the old one around a central spine.",
    "book-flip.webm"
  ),
  pageStyle(
    "roll",
    "Roll",
    "The old page rolls away like a scroll as the new one unrolls.",
    "roll.webm"
  ),
  pageStyle(
    "fold",
    "Fold",
    "The old page folds inward along its centre as the new one emerges.",
    "fold.webm"
  ),
  pageStyle(
    "glitch",
    "Glitch",
    "The old page jitters out in stepped frames before the new one snaps in.",
    "glitch.webm"
  ),
  pageStyle(
    "iris-wipe",
    "Iris Wipe",
    "An iris closes on the old page and opens on the new one.",
    "iris-wipe.webm"
  ),
  {
    css: "registry/ui/ui-transition.css",
    description:
      "The tk() class helper, useTransitionNames and the tk-* View Transition Classes every UI component composes with React's <ViewTransition>.",
    files: ["registry/ui/ui-transition.ts"],
    group: "ui",
    kind: "core",
    name: "ui/ui-transition",
    title: "UI Transition",
  },
  {
    description:
      "The active pill glides to the selected tab and the panel slides in the direction you moved.",
    files: ["registry/ui/tabs.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/tabs",
    title: "Tabs",
  },
  {
    description:
      "An iOS-style segmented control whose thumb glides to the chosen option with a slight spring.",
    files: ["registry/ui/segmented-control.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/segmented-control",
    title: "Segmented Control",
  },
  {
    description:
      "Opening a panel grows its item and the items below glide down, with no height measured in JavaScript.",
    files: ["registry/ui/accordion.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/accordion",
    title: "Accordion",
  },
  {
    css: "registry/ui/carousel.css",
    description:
      "Slides push in like a track from the side you moved toward, with arrows, dots, swipe, keyboard and optional autoplay.",
    files: ["registry/ui/carousel.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/carousel",
    title: "Carousel",
  },
  {
    description:
      "iOS-style push and pop screens in a fixed frame. Screens slide in the direction you travel and the title glides into the back button.",
    files: ["registry/ui/stack-navigator.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/stack-navigator",
    title: "Stack Navigator",
  },
  {
    css: "registry/ui/step-wizard.css",
    description:
      "A multi-step form whose panels slide in the direction you move and whose progress indicator glides between steps.",
    files: ["registry/ui/step-wizard.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/step-wizard",
    title: "Step Wizard",
  },
  {
    css: "registry/ui/dynamic-island.css",
    description:
      "A pill that springs between sizes as its state changes, with the content blurring across inside it.",
    files: ["registry/ui/dynamic-island.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/dynamic-island",
    title: "Dynamic Island",
  },
  {
    css: "registry/ui/status-button.css",
    description:
      "A button that morphs from idle to loading to success or error, resizing smoothly while its label and icon crossfade.",
    files: ["registry/ui/status-button.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/status-button",
    title: "Status Button",
  },
  {
    description:
      "Changed digits roll up when the number grows and down when it shrinks. Separators and unchanged digits stay put.",
    files: ["registry/ui/number-flip.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/number-flip",
    title: "Number Flip",
  },
  {
    css: "registry/ui/add-to-cart.css",
    description:
      'The product image flies into the cart button, the badge count rolls up and the button label morphs to "Added".',
    files: ["registry/ui/add-to-cart.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/add-to-cart",
    title: "Add to Cart",
  },
  {
    css: "registry/ui/morphing-popover.css",
    description: "A trigger that morphs into its popover surface and back.",
    files: ["registry/ui/morphing-popover.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/morphing-popover",
    title: "Morphing Popover",
  },
  {
    css: "registry/ui/product-gallery.css",
    description:
      "A hero image with a thumbnail strip. The chosen thumbnail grows into the hero while the old hero shrinks back into its slot.",
    files: ["registry/ui/product-gallery.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/product-gallery",
    title: "Product Gallery",
  },
  {
    css: "registry/ui/layout-switcher.css",
    description:
      "Toggle a collection between grid and list. Every card, avatar, name and stat glides to its new spot.",
    files: ["registry/ui/layout-switcher.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/layout-switcher",
    title: "Layout Switcher",
  },
  {
    css: "registry/ui/animated-list.css",
    description:
      "A list whose items pop in, fade out and glide into place as they change.",
    files: ["registry/ui/animated-list.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/animated-list",
    title: "Animated List",
  },
  {
    description:
      "Filter a grid with chips and search. Matches reflow into place, the rest pop out, and new items pop in one after another.",
    files: ["registry/ui/filter-grid.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/filter-grid",
    title: "Filter Grid",
  },
  {
    description:
      "Click a column header to sort and the rows glide to their new positions. Filtered rows fade out while the rest close the gap.",
    files: ["registry/ui/sortable-table.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/sortable-table",
    title: "Sortable Table",
  },
  {
    description:
      "Drag cards between columns, or move them with the keyboard. The card glides into place, its neighbours make room and the column counts roll.",
    files: ["registry/ui/kanban-board.tsx"],
    group: "ui",
    kind: "component",
    name: "ui/kanban-board",
    title: "Kanban Board",
  },
];

export const getItem = (name: string) =>
  items.find((item) => item.name === name);
